name: hypercube_client

description: A Dart package for interacting with the HyperCube platform.

version: 0.1.0 # Update with your package version

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  foundation: ^0.0.5 # Or the latest version you're using
  firedart: ^0.9.8 # Or the latest version you're using
  network_info_plus: ^6.1.1

# Dev dependencies
dev_dependencies:
  lints: ^2.1.1
  test: ^1.16.0

environment:
  sdk:  '^3.5.0'
